# Generated by Django 6.0.1 on 2026-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
