# Generated by Django 6.0.1 on 2026-01-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_college_view_count_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='brochures_list/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
