# Generated by Django 6.0.1 on 2026-01-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_adcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcontent',
            name='image_mongo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brochure',
            name='file_mongo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='brochure_mongo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='brochures_list/'),
        ),
    ]
